#!/usr/bin/env bash
# =============================================================================
# Matugen Dynamic Cursor Generator
# 
# This script reads colors generated by Matugen, recolors the raw cursor SVG 
# assets, compiles them into a Hyprcursor theme, and instantly hot-reloads 
# Hyprland and GTK to apply the new cursor natively.
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
readonly SRC_BASE="$HOME/.local/share/hyprcursor-matugen/src"
readonly OUT_BUILD="/tmp/hyprcursor-matugen-build"
readonly COLORS_LUA="$HOME/.config/matugen/generated/hyprland-colors.lua"
readonly LOCK_FILE="/tmp/matugen-cursor.lock"
readonly LOG_FILE="/tmp/matugen-cursor.log"

# Prevent concurrent executions which could corrupt the build directory
exec 9>"$LOCK_FILE"
if ! flock -w 60 9; then 
  echo "[matugen-cursor] Lock timeout, skipping execution." >> "$LOG_FILE" 2>&1
  exit 0
fi

# -----------------------------------------------------------------------------
# Utility Functions
# -----------------------------------------------------------------------------
log() { 
  echo "[matugen-cursor] $(date '+%Y-%m-%d %H:%M:%S') - $*" >> "$LOG_FILE" 2>&1
}

die() { 
  log "CRITICAL ERROR: $*"
  exit 1
}

# Extracts the current system cursor size from GNOME settings
fetch_cursor_size() {
  local size
  size=$(gsettings get org.gnome.desktop.interface cursor-size 2>/dev/null | grep -oE '[0-9]+' | head -n1 || true)
  [[ -z "$size" || ! "$size" =~ ^[0-9]+$ ]] && size="18"
  
  # Clamp the size to safe boundaries
  echo $(( size < 16 ? 16 : (size > 128 ? 128 : size) ))
}

# Ensures the colors file is fully written before proceeding
wait_for_colors() {
  for _ in {1..5}; do
    if [[ -s "$COLORS_LUA" ]] && grep -q "primary" "$COLORS_LUA" 2>/dev/null; then 
      return 0
    fi
    sleep 0.2
  done
  die "Colors file missing or empty: $COLORS_LUA"
}

# Extracts a specific color from the Matugen generated Lua file
get_color() {
  local key="$1" fallback="$2"
  local raw
  raw=$(grep -E "^\s*$key\s*=" "$COLORS_LUA" 2>/dev/null | head -n1 | cut -d'"' -f2 || true)
  [[ -n "$raw" ]] && echo "$raw" || echo "$fallback"
}

# -----------------------------------------------------------------------------
# Core Build Logic
# -----------------------------------------------------------------------------

# Recolors all raw SVG templates using the active system colors
build_cursors() {
  log "Building raw SVG assets..."
  
  # Convert hex colors to uppercase for sed replacement matching
  local fill_up outline_up
  fill_up=$(echo "$PRIMARY" | tr 'a-f' 'A-F')
  outline_up=$(echo "$BACKGROUND" | tr 'a-f' 'A-F')

  # Clean previous temporary builds
  rm -rf "$OUT_BUILD" "/tmp/theme_matugen-cursor-"*
  mkdir -p "$OUT_BUILD/cursors"
  
  # Generate the manifest required by hyprcursor
  cat > "$OUT_BUILD/manifest.hl" <<EOF
name = $THEME_NAME
description = Matugen generated cursor
version = 1.0
cursors_directory = cursors
EOF

  # Iterate through all available cursor shapes
  for cursor_dir in "$SRC_BASE"/*; do
    [[ -d "$cursor_dir" ]] || continue
    local name
    name=$(basename "$cursor_dir")
    
    mkdir -p "$OUT_BUILD/cursors/$name"
    cp "$cursor_dir/meta.hl" "$OUT_BUILD/cursors/$name/meta.hl" 2>/dev/null || true
    
    # Improve anti-aliasing for the cursors
    sed -i "s/resize_algorithm = none/resize_algorithm = bilinear/g" "$OUT_BUILD/cursors/$name/meta.hl" 2>/dev/null || true
    
    # Recolor each SVG component in the shape directory
    for svg in "$cursor_dir"/*.svg; do
      [[ -f "$svg" ]] || continue
      local bname
      bname=$(basename "$svg")
      local tmp_svg
      tmp_svg=$(mktemp)
      
      # The base template uses #E0DEF4 for fill and #191724 for outline
      if sed -e "s/#E0DEF4/$fill_up/gI" -e "s/#191724/$outline_up/gI" "$svg" > "$tmp_svg"; then
        mv "$tmp_svg" "$OUT_BUILD/cursors/$name/$bname"
      else
        rm -f "$tmp_svg"
      fi
    done
  done
}

# Compiles the recolored SVGs into native .hlc binaries
compile_theme() {
  log "Compiling .hlc binaries via hyprcursor-util..."
  local build_out="/tmp/theme_$THEME_NAME"
  rm -rf "$build_out"
  
  if ! timeout 30 hyprcursor-util --create "$OUT_BUILD" >> "$LOG_FILE" 2>&1; then
    die "hyprcursor-util compilation failed. Check logs."
  fi
}

# Installs the compiled theme to the user's icon directory with legacy fallbacks
install_theme() {
  log "Installing theme to ~/.local/share/icons..."
  local icon_dest="$HOME/.local/share/icons/$THEME_NAME"
  local build_out="/tmp/theme_$THEME_NAME"
  
  # Atomic replacement of the theme directory
  rm -rf "$icon_dest" "$icon_dest.tmp"
  cp -r "$build_out" "$icon_dest.tmp"
  mv "$icon_dest.tmp" "$icon_dest"
  
  cp "$OUT_BUILD/manifest.hl" "$icon_dest/manifest.hl" 2>/dev/null || true

  # Ensure GTK/XWayland apps gracefully fall back to Adwaita instead of crashing
  cat > "$icon_dest/index.theme" <<EOF
[Icon Theme]
Name=$THEME_NAME
Comment=Matugen generated dynamic cursor
Inherits=Adwaita,hicolor
EOF

  # Set the system-wide default inheritance
  mkdir -p "$HOME/.local/share/icons/default" "$HOME/.icons/default"
  echo -e "[Icon Theme]\nInherits=$THEME_NAME,Adwaita,hicolor" > "$HOME/.local/share/icons/default/index.theme"
  echo -e "[Icon Theme]\nInherits=$THEME_NAME,Adwaita,hicolor" > "$HOME/.icons/default/index.theme"
}

# Applies the new theme instantly to the live environment
apply_live() {
  log "Triggering live environment hot-reloads..."
  
  # Tell GTK applications about the new theme
  gsettings set org.gnome.desktop.interface cursor-theme "$THEME_NAME" 2>/dev/null || true
  
  # Export clean Lua environment variables for Hyprland to source
  mkdir -p "$HOME/.config/hypr/generated"
  cat > "$HOME/.config/hypr/generated/cursor.lua" <<EOF
hl.env("XCURSOR_THEME", "$THEME_NAME")
hl.env("HYPRCURSOR_THEME", "$THEME_NAME")
hl.env("XCURSOR_SIZE", "$SIZE")
hl.env("HYPRCURSOR_SIZE", "$SIZE")
EOF

  # Force Hyprland to instantly adopt the new cursor
  timeout 5 hyprctl setcursor "$THEME_NAME" "$SIZE" >> "$LOG_FILE" 2>&1 || true
  timeout 5 hyprctl reload >> "$LOG_FILE" 2>&1 || true
  
  log "Cursor update complete."
}

# -----------------------------------------------------------------------------
# Main Execution
# -----------------------------------------------------------------------------
main() {
  [[ -d "$SRC_BASE" ]] || die "Cursor source base missing: $SRC_BASE"
  
  readonly SIZE="$(fetch_cursor_size)"
  wait_for_colors
  
  readonly PRIMARY="$(get_color "primary" "#b2d189")"
  readonly BACKGROUND="$(get_color "background" "#12140e")"
  
  # We append the hex code as a cache-busting suffix. 
  # This forces Hyprland to load the new cursor from disk instantly.
  readonly THEME_NAME="matugen-cursor-${PRIMARY:1}"
  
  log "--- Starting Build ---"
  log "Primary: $PRIMARY | Background: $BACKGROUND | Size: $SIZE"
  
  build_cursors
  compile_theme
  install_theme
  apply_live
}

main
